# Codecov configuration for DreamerV3
# See: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 90% # Overall project goal
        threshold: 1% # Allow 1% decrease without failing
        informational: false # Fail if below target

    patch:
      default:
        target: 80% # Minimum coverage for new code
        threshold: 5%
        informational: false

  ignore:
    # Test files
    - "*/tests/*"
    - "*/perf/*"
    - "*_test.py"
    # Visualization utilities
    - "plot.py"
    - "scores/view.py"
    - "*/viz/*"
    - "*visualizer.py"
    - "*_viz.py"
    # Interactive modules
    - "*/interactive.py"
    - "*/manual_*.py"
    # Setup files
    - "setup.py"
    - "*/setup.py"
    # Docker entrypoint
    - "entrypoint.sh"
    # Local development
    - ".local/**"

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true
